# Site settings
title: Python programming, web, data science
email: pawelmhm+github_blog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Blog about programming (Python) and occasionally about data analysis
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pawelmhm.github.io" # the base hostname & protocol for your site
github_username:  pawelmhm
author: Pawel Miech

# Build settings
markdown: kramdown
theme: minima
